name: 'ManifestBot'
description: 'ManifestBot updates the Penguin Statistics manifests repository to deploy a specified version of resources.'

inputs:
  file-path:
    description: 'The path to values-override.yaml relative to the manifest repository.'
    required: true

  version-path:
    description: 'The path to the version field in values-override.yaml.'
    required: true
    default: 'image.tag'

  version:
    description: 'The version of the resources to deploy.'
    required: true

  token:
    description: 'The token to use to push to the manifest repository.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'ManifestBot: Checkout manifests'
      uses: 'actions/checkout@v4'
      with:
        repository: 'imgg-devops/manifests'
        token: ${{ inputs.token }}

    - name: 'ManifestBot: Use yq to update manifests'
      shell: bash
      run: |
        sudo wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq;
        sudo chmod +x /usr/bin/yq;
        yq eval -i ".${{ inputs.version-path }} = \"${{ inputs.version }}\"" "${{ inputs.file-path }}"
    
    - name: 'ManifestBot: Commit and Push'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        git config --global user.name "Penguin Statistics DevOps"
        git config --global user.email "devops@penguin-stats.io"
        git add .
        git commit -m "${{ inputs.file-path }}: update to ${{ inputs.version }}"
        git push
